---
title: '**PSYC8863 Practical Assignment**'
subtitle: Latent Variable Model
output:
  html_document:
    theme: journal
    footer: ''
    highlight: pygments
    toc: yes
    toc_depth: 4
    toc_float: yes
    df_print: kable
    code_folding: 
  word_document:
    toc: no
    toc_depth: 3
    df_print: kable
    highlight: pygments
  rmarkdown::html_vignette:
    toc: yes
    toc_depth: 4
  pdf_document:
    toc: yes
    toc_depth: '4'
tags: []
editor_options:
  chunk_output_type: console
csl: utils/apa.csl
---
# Presetting for figures and knit options
```{r, set.seed(333), include=FALSE, warning=FALSE, message=TRUE}
library(knitr)
options(knitr.kable.NA = "",
        digits = 2)

figheight <- 6
figwidth <- 6 * 1.618034

knitr::opts_chunk$set(
  comment = ">",
  dpi = 500,
  fig.path = "figures/",
  tidy = TRUE,
  fig.height=figheight,
  fig.width=figwidth, 
  fig.align = "center"
)

```

# Methods

## Packages & Data

### Packages & convenient functions
```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(easystats)
library(lavaan)

set.seed(333)

# Convenient functions
# Descriptive statistics
descriptive_statistics <- function(df, begins_with){
  df %>% 
    select(dplyr::starts_with(begins_with)) %>% 
    report() %>% 
    as.data.frame() %>% 
    select(-one_of(c("n_Obs", "Median", "MAD"))) %>% 
    print()
  
  plot(df %>% 
    select(dplyr::starts_with(begins_with)) %>% 
    bayestestR::estimate_density(method = "KernSmooth") %>% 
    plot() + 
    labs(x = "", y = "") +
    see::theme_modern())
}
```


### Data
```{r warning=FALSE, message=FALSE}
# Read STATA data
data <- haven::read_dta("Dataset/LVM54.dta") |> 
  mutate(sex = as.factor(sex))  # male is 0, female is 1

# Define variable labels from STATA data
var_labels <- data.frame("name" = names(data),
                         "label" = sapply(data, function(x) attr(x, "label"))  |> as.character())
```


## Descriptive
```{r warning=FALSE, message=FALSE}
data |> 
  mutate(sex = ifelse(sex == 0, "M", "F")) |> 
  report::report_participants()
# "300 participants (50.0% females)"

# Describe categorical variable
data |> 
  select(sex) |> 
  ggplot(aes(x = sex)) +
  geom_bar(fill = "#2196F3") +
  ggtitle("Distribution of Gender") +
  ylab("") +
  scale_x_discrete(labels = c("Males", "Females")) +
  see::theme_modern()

# Check for MVN assumption and skewness for all variables
mvn_data <- data |> 
  select(-sex) |>
  MVN::mvn(mvnTest = "dh", 
           univariateTest = "SW",
           univariatePlot = "histogram")  # method is Doornik-Hansen
mvn_data

# Save descriptive statistics 
# descriptive_table <- mvn_data$Descriptives |> 
#   as.data.frame() |> 
#   mutate_if(is.numeric, round, digits = 2) |> 
#   write.csv(descriptive_table, "figures/descriptive_table.csv", row.names = TRUE)

# Check for MVN assumption and skewness for all variables but ED
data |> 
  select(-sex, -edscore) |>
  MVN::mvn(mvnTest = "dh", 
           univariateTest = "SW")
```


## Question 1 and 2
```{r warning=FALSE, message=FALSE}
# covariance structure between perf items
cor_perf <- data |> 
  select(starts_with("perf")) |> 
  correlation::correlation()
cor_perf

# covariance structure between emreg items
cor_emreg <- data |> 
  select(starts_with("emreg")) |> 
  correlation::correlation()
cor_emreg

cor_table <- rbind(cor_perf, cor_emreg)
# Save corr table
# cor_table |>
#   as.data.frame() |>
#   mutate_if(is.numeric, round, digits = 2) |>
#   mutate("95% CI" = paste0("[", CI_low, ",", CI_high, "]")) |> 
#   mutate(p = "< .001***") |> 
#   select(Parameter1, Parameter2, r, "95% CI", p) |> 
#   write.csv("figures/cor_table.csv", row.names = FALSE)

# measurement model
model_measurement <- "
# Measurement model
perfectionism =~ perf1 + perf2 + perf3 + perf4 + perf5
em_regulation =~ emreg1 + emreg2 + emreg3 + emreg4 + emreg5
"

fit_measurement <- sem(model_measurement, data = data)
sem_measurement <- summary(fit_measurement, fit.measures = TRUE, standardized = TRUE)

as.data.frame(t(as.data.frame(sem_measurement$FIT))) |> 
  select(chisq, df, pvalue, cfi, rmsea, rmsea.pvalue, srmr, aic, bic)
```

## Question 3
```{r warning=FALSE, message=FALSE}
# SEM model
model <- "
# Measurement model
perfectionism =~ perf1 + perf2 + perf3 + perf4 + perf5
em_regulation =~ emreg1 + emreg2 + emreg3 + emreg4 + emreg5

# Structural model
## Regressions
perfectionism ~ edscore
em_regulation ~ edscore
"

fit_model <- sem(model, data = data, se = "robust")
summary(fit_model, fit.measures = TRUE, standardized = TRUE)
# 
# semTable::semTable(fit_model, type = "html", file = "figures/sem2")
```


## Question 4

### Measurement invariance testing
```{r warning=FALSE, message=FALSE}
fit_model_group1 <- sem(model, data = data, se = "robust", group = "sex")
summary(fit_model_group1, fit.measures = TRUE, standardized = TRUE)
m1 <- fitMeasures(fit_model_group1)[names = c("cfi", "tli")]
fit_model_group2 <- sem(model, data = data, se = "robust", group = "sex",
                       group.equal = c("loadings"))
summary(fit_model_group2, fit.measures = TRUE, standardized = TRUE)
m2 <- fitMeasures(fit_model_group2)[names = c("cfi", "tli")]
fit_model_group3 <- sem(model, data = data, se = "robust", group = "sex",
                       group.equal = c("loadings", "intercepts"))
summary(fit_model_group3, fit.measures = TRUE, standardized = TRUE)
m3 <- fitMeasures(fit_model_group3)[names = c("cfi", "tli")]

lavTestLRT(fit_model_group1, fit_model_group2, fit_model_group3)
# Not sig diff => metric measurement invariance can be assumed
# Not sig diff => metric scalar invariance can be assumed

round(m1 - m2, 3)
#  cfi   tli 
#0.000 0.002 
round(m2 - m3, 3)
#   cfi    tli 
#  0   0 
```

### Gender invariance testing
```{r warning=FALSE, message=FALSE}
# constrained for perf
model_perf_const <- "
# Measurement model
perfectionism =~ perf1 + perf2 + perf3 + perf4 + perf5
em_regulation =~ emreg1 + emreg2 + emreg3 + emreg4 + emreg5

# Structural model
## Regressions
perfectionism ~ c(b1, b1)*edscore
em_regulation ~ edscore
"
fit_perf_cons <- sem(model_perf_const, data = data, se = "robust", group = "sex",
                     group.equal = c("loadings", "intercepts"))
summary(fit_perf_cons, fit.measures = TRUE, standardized = TRUE)
summary(fit_model_group3, fit.measures = TRUE, standardized = TRUE)
anova(fit_perf_cons, fit_model_group3)
# sig diff, perf variant by gender
perf_cons <- fitMeasures(fit_perf_cons)[names = c("cfi", "tli")]
round(m3 - perf_cons, 3)

# constrained for em
model_em_const <- "
# Measurement model
perfectionism =~ perf1 + perf2 + perf3 + perf4 + perf5
em_regulation =~ emreg1 + emreg2 + emreg3 + emreg4 + emreg5

# Structural model
## Regressions
perfectionism ~ edscore
em_regulation ~ c(b2, b2)*edscore
"
fit_em_cons <- sem(model_em_const, data = data, se = "robust", group = "sex",
                     group.equal = c("loadings", "intercepts"))
summary(fit_em_cons, fit.measures = TRUE, standardized = TRUE)
anova(fit_em_cons, fit_model_group3)
# sig diff, em variant by gender
em_cons <- fitMeasures(fit_em_cons)[names = c("cfi", "tli")]
round(m3 - em_cons, 3)
```



# Plotting
```{r sem_plot_male, warning=FALSE, message=FALSE}
# Create plot data
sem_parameters <-model_parameters(fit_model_group3, standardize = TRUE)
data_plot <- see::data_plot(sem_parameters, ci=FALSE)

# Rename nodes and edges
data_plot$nodes <- mutate(data_plot$nodes,
  Name = str_replace(Name, "perfectionism", "Perfectionism"),
  Name = str_replace(Name, "em_regulation", "Emotional\nRegulation"),
  Name = str_replace(Name, "edscore", "ED\nSymptom\nScore"))
data_plot$edges <- mutate(data_plot$edges,
  from = str_replace(from, "perfectionism", "Perfectionism"),
  from = str_replace(from, "em_regulation", "Emotional\nRegulation"),
  from = str_replace(from, "edscore", "ED\nSymptom\nScore"))
data_plot$edges <- mutate(data_plot$edges,
  to = str_replace(to, "perfectionism", "Perfectionism"),
  to = str_replace(to, "em_regulation", "Emotional\nRegulation"),
  to = str_replace(to, "edscore", "ED\nSymptom\nScore"))

# Separate plot data into male and female
## Male
data_plot_male <- data_plot |> 
  map(~slice(., 1:13))

## Female
data_plot_female <- data_plot |> 
  map(~slice(., c(1:3, 14:n())))
data_plot_female$edges <- data_plot_female$edges |> 
  slice(4:n())
set.seed(333)
# Plot for Male
sem_plot_male <- tidygraph::tbl_graph(data_plot_male$nodes, data_plot_male$edges) |> 
  ggraph::ggraph(layout = 'fr') +
  # Correlation
  ggraph::geom_edge_arc(aes(
                    alpha = as.numeric(Component == "Correlation"),
                    label = Label_Correlation,
                    color = Coefficient),
                    strength = 0.3,
                    label_dodge = unit(4, "mm"),
                    angle_calc = "along", 
                    edge_width = 0.5,
                    label_size = 2.7,
                    linetype = 2,
                    arrow = arrow(type = "closed", length = unit(3, "mm"), ends = "both"),
                    start_cap = ggraph::circle(-12, 'mm'), end_cap = ggraph::circle(-12, 'mm')) +
  # Loading
  ggraph::geom_edge_link(aes(
                     alpha = as.numeric(Component == "Loading"),
                     label = Label_Loading,
                     color = Coefficient),
                     label_dodge = unit(2, "mm"),
                     angle_calc = "along", 
                     edge_width = 0.3,
                     label_size = 2.7,
                     #check_overlap = TRUE,
                     arrow = arrow(type = "closed", length = unit(3, "mm")),
                     start_cap = ggraph::circle(0, 'mm'), end_cap = ggraph::circle(-12, 'mm')) +
  # Regression
  ggraph::geom_edge_link(aes(
                     alpha = as.numeric(Component == "Regression"),
                     label = Label_Regression,
                     color = Coefficient),
                     label_dodge = unit(2, "mm"),
                     angle_calc = "along", 
                     edge_width = 0.9,
                     label_size = 2.7,
                     #check_overlap = TRUE,
                     arrow = arrow(type = "closed", length = unit(3, "mm")),
                     start_cap = ggraph::circle(0, 'mm'), end_cap = ggraph::circle(-12, 'mm')) +
   ggraph::geom_node_point(aes(colour = Name, size = Latent)) +
  ggraph::geom_node_text(aes(label = Name), size = 3)  +
  ggraph::scale_edge_colour_gradient2(
    guide = FALSE,
    high = "#6aa84f",
    mid = "#bcbcbc",
    low = "#f50a0a"
  ) +
  scale_alpha(guide = FALSE, range = c(0, 1)) +
  scale_size_manual(values=c("TRUE"=22, "FALSE"=30)) +
  scale_x_continuous(expand = expansion(c(0.07, 0.07))) +
  scale_y_continuous(expand = expansion(c(0.07, 0.07))) +
  scale_color_manual(values=c(
    "Perfectionism"="#f383a9",
    "perf1"="#f895b7", 
    "perf2"="#f396b5", 
    "perf3"="#f58caf", 
    "perf4"="#f8adc5", 
    "perf5"="#F8BBD0",
                              
    "Emotional\nRegulation"="#FF9800", 
    "emreg1"="#f3b14f", 
    "emreg2"="#fcd397", 
    "emreg3"="#f7bf6d",
    "emreg4"="#FFCC80", 
    "emreg5"="#FFE0B2",
                              
    "ED\nSymptom\nScore"="#a88ade")) +
  ggraph::theme_graph() +
  theme(legend.position = "none") + 
  ggtitle("Final model for Male")
sem_plot_male
#ggsave("figures/sem_plot_male.png", sem_plot_male, height=figheight*1.2, width=figwidth, dpi=600)
```


```{r sem_plot_female, warning=FALSE, message=FALSE}
# Plot for Female
sem_plot_female <- tidygraph::tbl_graph(data_plot_female$nodes, data_plot_female$edges) |> 
  ggraph::ggraph(layout = 'fr') +
  # Correlation
  ggraph::geom_edge_arc(aes(
                    alpha = as.numeric(Component == "Correlation"),
                    label = Label_Correlation,
                    color = Coefficient),
                    strength = 0.3,
                    label_dodge = unit(4, "mm"),
                    angle_calc = "along", 
                    edge_width = 0.5,
                    label_size = 2.7,
                    linetype = 2,
                    arrow = arrow(type = "closed", length = unit(3, "mm"), ends = "both"),
                    start_cap = ggraph::circle(-12, 'mm'), end_cap = ggraph::circle(-12, 'mm')) +
  # Loading
  ggraph::geom_edge_link(aes(
                     alpha = as.numeric(Component == "Loading"),
                     label = Label_Loading,
                     color = Coefficient),
                     label_dodge = unit(2, "mm"),
                     angle_calc = "along", 
                     edge_width = 0.3,
                     label_size = 2.7,
                     #check_overlap = TRUE,
                     arrow = arrow(type = "closed", length = unit(3, "mm")),
                     start_cap = ggraph::circle(0, 'mm'), end_cap = ggraph::circle(-12, 'mm')) +
  # Regression
  ggraph::geom_edge_link(aes(
                     alpha = as.numeric(Component == "Regression"),
                     label = Label_Regression,
                     color = Coefficient),
                     label_dodge = unit(2, "mm"),
                     angle_calc = "along", 
                     edge_width = 0.9,
                     label_size = 2.7,
                     #check_overlap = TRUE,
                     arrow = arrow(type = "closed", length = unit(3, "mm")),
                     start_cap = ggraph::circle(0, 'mm'), end_cap = ggraph::circle(-12, 'mm')) +
   ggraph::geom_node_point(aes(colour = Name, size = Latent)) +
  ggraph::geom_node_text(aes(label = Name), size = 3)  +
  ggraph::scale_edge_colour_gradient2(
    guide = FALSE,
    high = "#6aa84f",
    mid = "#bcbcbc",
    low = "#f50a0a"
  ) +
  scale_alpha(guide = FALSE, range = c(0, 1)) +
  scale_size_manual(values=c("TRUE"=22, "FALSE"=30)) +
  scale_x_continuous(expand = expansion(c(0.07, 0.07))) +
  scale_y_continuous(expand = expansion(c(0.07, 0.07))) +
  scale_color_manual(values=c(
    "Perfectionism"="#f383a9",
    "perf1"="#f895b7", 
    "perf2"="#f396b5", 
    "perf3"="#f58caf", 
    "perf4"="#f8adc5", 
    "perf5"="#F8BBD0",
                              
    "Emotional\nRegulation"="#FF9800", 
    "emreg1"="#f3b14f", 
    "emreg2"="#fcd397", 
    "emreg3"="#f7bf6d",
    "emreg4"="#FFCC80", 
    "emreg5"="#FFE0B2",
                              
    "ED\nSymptom\nScore"="#a88ade")) +
  ggraph::theme_graph() +
  theme(legend.position = "none") + 
  ggtitle("Final Model for Female")
sem_plot_female
#ggsave("figures/sem_plot_female.png", sem_plot_female, height=figheight*1.2, width=figwidth, dpi=600)
```



